# Generated by Django 5.0.1 on 2024-01-30 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id_prioridade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_profile', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_avatar', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True)),
                ('icon_url', models.CharField(blank=True, max_length=256)),
                ('integrantes', models.ManyToManyField(to='calls.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id_call', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.equipe')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.prioridade')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.status')),
                ('criado_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criado_para', to='calls.usuario')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to='calls.usuario')),
            ],
        ),
    ]
