# Generated by Django 5.0.1 on 2024-01-29 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id_call', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id_prioridade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prioridade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True)),
                ('icon_url', models.CharField(blank=True, max_length=256)),
                ('calls', models.ManyToManyField(to='calls.call')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.prioridade'),
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.status'),
        ),
    ]
